baseURL = 'https://apps.crsu.org.uk'
title = "CRSU Apps"
author = "Ryan J Field"
copyright = "CRSU 2024"

timeZone = 'Europe/London'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = "hugo-bootstrap-theme"
themesdir = "themes"

disablePathToLower = true
disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"

[markup.goldmark.renderer]
unsafe= true

[params]
  # Site Params

  # Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
  # https://gohugo.io/templates/internal/#open-graph
  # https://gohugo.io/templates/internal/#twitter-cards
  # https://schema.org/Thing
  # https://schema.org/Article
  description = "The CRSU provides apps for meta-analysis"
  images = ['images/logo.svg','images/site-feature-image.png']
  #mainMenuLogo = "images/logo.svg"

  # For favicons
  ## Chrome Browser
  themeColor = "#fff"

  [params.options]
    bootStrapJs = true
    breadCrumb = false
    listCategoryFilter = false
    listTagFilter = false

[menus]
  [[menus.main]]
    name = "MetaPairwise"
    url = "MetaPairwise"
    weight = 10
  [[menus.main]]
    name = "MetaInsight"
    url = "MetaInsight"
    weight = 20
    title = "Made with ❤️ by the Hugo Bootstrap Theme team"
  [[menus.main]]
    name = "MetaInsightCOVID"
    url = "MetaInsightCOVID"
    weight = 30
  [[menus.main]]
    name = "DTA-Primer"
    url = "DTA-Primer"
    weight = 40
    title = "Made with ❤️ by the Hugo Bootstrap Theme team"
  [[menus.main]]
    name = "MetaDTA"
    url = "MetaDTA"
    weight = 50
  [[menus.main]]
    name = "MetaBayesDTA"
    url = "MetaBayesDTA"
    weight = 60
    title = "Made with ❤️ by the Hugo Bootstrap Theme team"
  [[menus.main]]
    name = "MetaImpact"
    url = "MetaImpact"
    weight = 70
    title = "Made with ❤️ by the Hugo Bootstrap Theme team"
  [[menus.social]]
    name = "GitHub"
    pre = "<span class='fa-brands fa-github'></span>"
    url = "https://github.com/CRSU-Apps/"
    weight = 10
    title = "Visit our GitHub Organisation"

  [[menus.social]]
    name = "Twitter"
    pre = "<span class='fa-brands fa-x-twitter'></span>"
    url = "https://twitter.com/CRSU_News/"
    weight = 20
    title = "Follow us on X"